version: '3'
services:
  nodejs:
    build:
      context: .
   # image: node:16.13.2-alpine
    container_name: nodejs
    ports:
      - "3000:3000"
      - "587:587"
    volumes:
      - /var/lib/docker/volumes/abc:/var/data

volumes:
  abc:
